jobs/urls.py
from django.urls import path
from .views import *

app_name='jobs'
urlpatterns = [
    path('', jobs_all, name='jobs_all'),
    path('create/', job_create, name='job_create'),
    path('<str:slug>/edit/', job_update, name='job_update'),
    path('<str:slug>/delete/', job_delete, name='job_delete'),
    path('<str:slug>/', job_detail, name='job_detail'),
    
]

profiles/urls.py
from django.urls import path
from .views import *
app_name='profiles'
urlpatterns = [
    path('', profiles_all, name='profiles_all'),
    path('<str:slug>/', profile_detail, name='profile_detail'),
    path('<str:slug>/edit/', profile_update, name='profile_update'),
    path('<str:slug>/delete/', profile_delete, name='profile_delete'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.core.checks import messages
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.contrib.auth.models import User
from datetime import date
import random
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profiles/', null=True, blank=True)
    code = models.CharField(max_length=50, null=True, blank=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    birthdate = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
       
        if not self.slug:
            self.slug = slugify(self.user.username)
        
        super(Profile, self).save(*args, **kwargs)

def save_profile(sender, instance, created, **kwargs):
    if created:
        user = instance
        Profile.objects.create(user=user)


post_save.connect(save_profile, sender=User)


def delete_profile(sender, instance, **kwargs):
    user = instance.user
    user.delete()


post_delete.connect(delete_profile, sender=Profile)

profiles/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import *


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
        ]


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = [
            'image',
            'code',
            'phone',
            'birthdate',
            'description'
        ]

profiles/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from .forms import ProfileForm, UserForm
from django.contrib import messages
from django.contrib.auth import login as auth_login
from .models import *
from datetime import date
import os
# Create your views here.


def profiles_all(req):
    print(req)
    profiles_all = Profile.objects.all()
    paginator = Paginator(profiles_all, 1)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(req, 'profiles/profiles.html', {'page_obj': page_obj})


def profile_update(req, slug):

    message = ''
    user = req.user
    profile = user.profile
    
    form = ProfileForm(instance=profile)
    form2 = UserForm(instance=user)
    if req.method == 'POST':

        form = ProfileForm(req.POST, req.FILES, instance=profile)
        form2 = UserForm(req.POST, req.FILES, instance=user)
        if form.is_valid() and form2.is_valid():

            user = form2.save(commit=False)
            user.save()

            profile = form.save(commit=False)
            profile.user = user
            today = date.today()
            if profile.birthdate is not None:
                age = profile.birthdate.year
                profile.age = today.year - age
                if (today.year - age) < 20:
                    #messages.success(req, 'Your mesaage has been sent')
                    return redirect('profiles:profile_update', profile.slug)

            if profile.phone is not None:

                if len(profile.phone) != 11 and profile.phone[0] != 0 and profile.phone[1] != 1:
                    message = 'age should be enter correct phone number!!'
                    return redirect('profiles:profile_update', profile.slug)
            
            profile.save()

            auth_login(req, user)

            #messages.success(req, 'updated')
            return redirect('profiles:profile_detail', profile.slug)
        else:
            #messages.error(req, 'faild')
            return redirect('profiles:profile_update', profile.slug)

    return render(req, 'profiles/update.html', {'form': form, 'form2': form2, 'message': message})


def profile_detail(req, slug):
    print('..........')

    profile = Profile.objects.get(slug=slug)
    jobs = profile.job_set.all()
    return render(req, 'profiles/detail.html', {'profile': profile, 'jobs': jobs})


def profile_delete(req, slug):

    profile = Profile.objects.get(slug=slug)
    if req.method == 'POST':
        profile.delete()
        return redirect('accounts:login')
    return render(req, 'profiles/delete.html', {})

profiles/templates/profiles/delete.html
{% extends "base.html" %}


{% block content %}
  
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        
    </div>
    <input class="btn btn-primary" style="width: 80%; background-color: crimson; margin-left: 10%;margin-bottom: 20px;" type="submit" value="delete">
</form>




{% endblock content %}

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}



<section id="intro">
    <div class="carousel-item active">
        <div class="carousel-background"><img src="{% static 'imags/slider/slider1.jpg' %}" alt=""></div>
        <div class="carousel-container">
            <div class="carousel-content">
                <h2 class="font-color-white">Profile Result</h2>
                <p class="font-color-white width-100"><a href="index.html" class="font-color-white">Home /</a><a
                        href="Job_Category-2.html" class="font-color-white"> Profile </a>/ Details
                </p>
            </div>
        </div>
    </div>
</section>


<section id="job-Details">
    <div class="container background-color-full-white job-Details">
        <div class="Exclusive-Product">
            <h2 style="font-weight: bold;">{{profile.user.username}}</h2>
            {% if user.profile.slug == profile.slug %}
              <a href="{% url 'profiles:profile_delete' profile.slug %}" class="Apply-Now">Delete</a>
            <a href="{% url 'profiles:profile_update' profile.slug %}" class="Apply-Now">Edit</a>
            {% endif %}
            
            <h4>Email:</h4>
            <span style="font-size: 20px;">{{profile.user.email}}</span>
            
            <h4>Code:</h4>
            <span style="font-size: 20px;">{{profile.code}}</span>
            <h4>Phone:</h4>
            <span style="font-size: 20px;">{{profile.phone}}</span>
            <h4>Age:</h4>
            <span style="font-size: 20px;">{{profile.age}}</span>
        </div>
        {% if profile.image%}
                    <img src="{{profile.image.url}}" alt="John Doe" class="job-detail-img">
                {% else %}
                <img src="{% static 'images/profile.jpeg' %}" alt="John Doe" class="job-detail-img">
                {% endif %}
        <div class="Job-Description">
            <h4>Description</h4>
            <ul>
                {{profile.description}}
            </ul>
            <br>
            <br>
            <h4>My Jobs</h4>
            <div>
                {% for job in jobs %}
                <div class="detail" style="margin: 15px;">
                  <div class="media display-inline text-align-center">
                      {% if job.image %}
                        <img src="{{job.image.url}}" alt="John Doe" class="mr-3 " 
                      style="width: 120px; height: 120px;">
                      {% else %}
                      <img src="{% static 'images/job.jpeg' %}" alt="John Doe" class="mr-3 " 
                      style="width: 120px; height: 120px;">
                      {% endif %}
                      
            
                      <div class="media-body text-left  text-align-center">
                          <a href="{% url 'jobs:job_detail' job.slug %}"><h6>{{job.title}}</h6></a>
                          <i class="large material-icons">account_balance</i>
                          <span class="text">{{job.country}}</span>
                          <br />
                          <i class="large material-icons">place</i>
                          <span class="text font-size">{{job.location}}</span>
                          <div class="float-right margin-top text-align-center">
                              <a href="#" class="part-full-time">{{job.job_type}}</a>
                              <p class="date-time">Published at: {{job.pubished_at}}</p>
                          </div>
                      </div>
            
                  </div>
              </div>
              {% endfor %}
            </div>
        </div>
    </div>
    
</section>


<section id="comment" class="background-color-full-white-light">
    <div class="container">
        <div class="max-width-80">
            <h4>comment</h4>
            <a href="#" class="Share">Share</a>
            <div class="media border p-3">
                <img src="imags/comment1.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <h6>Rehmatun Nisal</h6>
                    <p>Suspendisse augue pulvinar placerat himenaeos odio nec turpis augue sem maecenas, faucibus erat
                        lacinia consectetur sapien suscipit vestibulum venenatis himenaeos.</p>
                </div>
            </div>
            <div class="media border p-3 ">
                <img src="imags/comment2.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <h6>Rehmatun Nisal</h6>
                    <p>Suspendisse augue pulvinar placerat himenaeos odio nec turpis augue sem maecenas, faucibus erat
                        lacinia consectetur sapien suscipit vestibulum venenatis himenaeos.</p>
                </div>
            </div>
            <div class="media border p-3 padding-none border-none">
                <img src="imags/comment3.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <form>
                        <textarea placeholder="Type commeny" required></textarea>
                        <button class="Post">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>




{% endblock content %}

profiles/templates/profiles/profiles.html
{% extends "base.html" %}
{% load static %}

{% block content %}




<div id="search-box">
    <div class="container search-box">
        <form action="search" method="GET" id="search-box_search_form_3"
            class="search-box_search_form d-flex flex-lg-row flex-column align-items-center justify-content-between ">
            <div class="d-flex flex-row align-items-center justify-content-start inline-block">
                <span class="large material-icons search">search</span>
                <input class="search-box_search_input" placeholder="Search Keyword" required="required" type="search">
                <select class="dropdown_item_select search-box_search_input">
                    <option>Category</option>
                    <option>Category1</option>
                    <option>Category2</option>
                </select>
                <span class="large material-icons search">place</span>
                <input class="search-box_search_input " placeholder="Location" required="required" type="search">
            </div>
            <button type="submit" class="search-box_search_button">Search Jobs</button>
        </form>
    </div>
</div>


<section id="resent-job-post" class="background-color-white">
    <div class="vertical-space-85"></div>
    <div class="container text-center">
        <h3 class="text-center">Profiles</h3>
        <div class="vertical-space-30"></div>
        <p class="max-width">Lorem ipsum tempus amet conubia adipiscing fermentum viverra gravida, mollis suspendisse
            pretium dictumst inceptos mattis euismod
        </p>
        <div class="vertical-space-60"></div>
        {% for profile in page_obj %}
        <div class="detail">
            <div class="media display-inline text-align-center">
                {% if profile.image%}
                <img src="{{profile.image.url}}" alt="John Doe" class="mr-3 " style="width: 120px; height: 120px;">
                {% else %}
                <img src="{% static 'images/profile.jpeg' %}" alt="John Doe" class="mr-3 "
                    style="width: 120px; height: 120px;">
                {% endif %}

                <div class="media-body text-left  text-align-center">
                    <a href="{% url 'profiles:profile_detail' profile.slug %}">
                        <h6>{{profile.user.username}}</h6>
                    </a>
                    <span>Code: </span>
                    <span class="text">{{profile.code}}</span>
                    <br />
                    <span>Phone: </span>
                    <span class="text font-size">{{profile.phone}}</span>
                    <div class="float-right margin-top text-align-center">
                        <p class="date-time">Age: {{profile.age}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}




        
        <div class="vertical-space-20"></div>
        <div class="profile-list">
        
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
        
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
        
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        
        </div>
    </div>
</section>
                {% endblock content %}

profiles/templates/profiles/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div style="margin-bottom: 20px; width:90%; margin-left: 5%;">

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="background-color: crimson;">{{message}}</div>
    <h4>User Data</h4>
    {{form2|crispy}}
    <h4>Profile Data</h4>
    {{form|crispy}}
    <button class="btn btn-primary" style="width: 100%;" type="submit">update</button>
  </form>
</div>


{% endblock content %}