accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
]

jobs/urls.py
from django.urls import path
from .views import *

app_name='jobs'
urlpatterns = [
    path('', jobs_all, name='jobs_all'),
    path('create/', job_create, name='job_create'),
    path('<str:slug>/edit/', job_update, name='job_update'),
    path('<str:slug>/delete/', job_delete, name='job_delete'),
    path('<str:slug>/', job_detail, name='job_detail'),
    
]

profiles/urls.py
from django.urls import path
from .views import *
app_name='profiles'
urlpatterns = [
    path('', profiles_all, name='profiles_all'),
    path('<str:slug>/', profile_detail, name='profile_detail'),
    path('<str:slug>/edit/', profile_update, name='profile_update'),
    path('<str:slug>/delete/', profile_delete, name='profile_delete'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Jobz-index</title>

    <script src="{% static 'js/4n2NXumNjtg5LPp6VXLlDicTUfA.js' %}"></script>
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.html' %}">
    <link rel="shortcut icon" type="image/ico" href="{% static 'images/favicon.html' %}" />

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'css/matrialize.css' %}" rel="stylesheet">

    <link href="{% static 'owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body style="background-color: burlywood;">

    <header class="header">

       

        <div class="header_container background-color-orange-light">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo_container">
                                <a href="">
                                    <img src="{% static 'imags/logo.png' %}" class="logo-text" alt="">
                                </a>
                            </div>
                            <nav class="main_nav_contaner ml-auto">
                                <ul class="main_nav">
                                    <li >
                                        <a href="{% url 'jobs:jobs_all' %}">Home</a>
                                    </li>

                                    
                                    <li><a href="{% url 'profiles:profiles_all' %}"> Prpfiles</a></li>
                                   
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'accounts:logout' %}">logout</a></li>
                                    {% else %}
                                    <li><a href="{% url 'accounts:login' %}">login</a></li>
                                    <li><a href="{% url 'accounts:signup' %}">signup</a></li>
                                    {% endif %}
                                </ul>
                                <div class=" Post-Jobs">
                                    <a href="{% url 'jobs:job_create' %}" class="">
                                        Post Jobs
                                    </a>
                                </div>
                                <div class="hamburger menu_mm menu-vertical">
                                    <i class="large material-icons font-color-white menu_mm menu-vertical">menu</i>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
            <div class="menu_close_container">
                <div class="menu_close">
                    <div></div>
                    <div></div>
                </div>
            </div>
            <div class="search">
                <form action="#" class="header_search_form menu_mm">
                    <input type="search" class="search_input menu_mm" placeholder="Search" required="required">
                    <button
                        class="header_search_button d-flex flex-column align-items-center justify-content-center menu_mm">
                        <i class="fa fa-search menu_mm" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
            <nav class="menu_nav">

                <ul>
                    <li>
                        <a href="#">Home

                    </li>
                    <li>
                        <a href="{% url 'jobs:jobs_all' %}">Jobs</a>

                    </li>
                    <li class="menu_mm"><a href="blog_page.html">Blog</a></li>
                    <li class="menu_mm"><a href="about_us.html">About</a></li>
                    <li class="menu_mm"><a href="contact.html">Contact</a></li>
                </ul>
            </nav>

        </div>
    </header>

<div style="margin-top: 80px;"></div>
    {% include "messages.html" %}
    <div style="margin-bottom: 150px;"></div>
    {% block content %}

    {% endblock content %}



    <footer id="footer" class="background-color-white">
        <div class="container">
            <div class="vertical-space-100"></div>
            <div class="row">
                <div class="col-lg-4 col-md-6 vertical-space-2">
                    <h5>About Us</h5>
                    <p class="paregraf">Tristique velit phasellus sed auctor leo eros luctus nibh fermentu ad impediet
                        rhonus dolor habitant purus velit aliquet donecurna ut in turpis faucibus</p>
                    <a href="#">
                        <i class="fa fa-facebook social-icon"></i></a>
                    <a href="#">
                        <i class="fa fa-twitter social-icon"></i></a>
                    <a href="#">
                        <i class="fa fa-pinterest-p social-icon"></i></a>
                    <a href="#">
                        <i class="fa fa-map-marker social-icon"></i></a>
                </div>
                <div class="col-lg-2 col-md-6 vertical-space-2">
                    <h5>Company</h5>
                    <div class="text">
                        <a href="#">About</a>
                        <a href="#">Support</a>
                        <a href="#">Tems</a>
                        <a href="#">Privacy</a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 vertical-space-2">
                    <h5>Supports</h5>
                    <div class="text">
                        <a href="#">About</a>
                        <a href="#">Support</a>
                        <a href="#">Tems</a>
                        <a href="#">Privacy</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 vertical-space-2">
                    <h5>Subscribe Us</h5>
                    <p>Get latest update and newsletter</p>
                    <div class="vertical-space-30"></div>
                    <form>
                        <input type="email" class="email " placeholder="Email Address " required="">
                        <span class="fa fa-envelope email-icone "></span>
                        <input type="submit" class="Subscribe" value="Subscribe">
                    </form>
                </div>
            </div>
            <div class="vertical-space-60"></div>
        </div>
        <div class="container-fluid background-color-orange main-footer">
            <div class="container text-center">
                <div class="vertical-space-30"></div>
                <p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
            </div>
        </div>
    </footer>


    <div class="modal" id="myModal">
        <div class="container">
            <div class="vertical-space-85"></div>
            <div class="modal-dialog modal-lg">
                <div class="modal-content">

                    <div class="modal-body">
                        <button class="button button-rounded  close" data-dismiss="modal">&times;</button>
                        <video class="" controls>
                            <source src="video/Pexels_Videos_2706.mp4" type="video/mp4">
                        </video>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script data-cfasync="false" src="{% static 'js/email-decode.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>
    <script>
        $(".search-icone").click(function () {
            // $(".menu").animate({height: "100vh"});
        });

    </script>
</body>

</html>

templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}