jobs/urls.py
from django.urls import path
from .views import *

app_name='jobs'
urlpatterns = [
    path('', jobs_all, name='jobs_all'),
    path('create/', job_create, name='job_create'),
    path('<str:slug>/edit/', job_update, name='job_update'),
    path('<str:slug>/delete/', job_delete, name='job_delete'),
    path('<str:slug>/', job_detail, name='job_detail'),
    
]

profiles/urls.py
from django.urls import path
from .views import *
app_name='profiles'
urlpatterns = [
    path('', profiles_all, name='profiles_all'),
    path('<str:slug>/', profile_detail, name='profile_detail'),
    path('<str:slug>/edit/', profile_update, name='profile_update'),
    path('<str:slug>/delete/', profile_delete, name='profile_delete'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
from profiles.models import Profile
import random 
from django.utils.text import slugify

job_type_choices = [
    ('part time','part-time'),
    ('full time','full-time'),
    ('internship','internship'),
    ('freelance','freelance'),
]
job_category_choices = [
    ('Education & Training','Education & Training'),
    ('Sales and Marketing','Sales and Marketing'),
    ('Computer Programing','Computer Programing'),
    ('Customer Support','Customer Support'),
    ('Design & Multimedia','Design & Multimedia'),
    ('Web Development','Web Development'),
    ('Medical/Pharma','Medical/Pharma'),
    ('Engineer/Architects','Engineer/Architects'),
]

class Job(models.Model):
    title = models.CharField(max_length=300)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='jobs/', null=True, blank=True)
    location = models.CharField(max_length=500)
    short_desc = models.CharField(max_length=500)
    description = models.TextField()
    category = models.CharField(max_length=200, choices=job_category_choices)
    vacancy = models.IntegerField()
    job_type = models.CharField(max_length=50, choices=job_type_choices)
    salary = models.IntegerField()
    pubished_at = models.DateField(auto_now_add=True)
    company = models.CharField(max_length=150, null=True,blank=True)
    country = models.CharField(max_length=150, null=True,blank=True)
    requerment = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        m =''
        temp=''
        
        if not self.slug:
            self.slug=slugify(self.title)
        temp = m = self.slug
        try:
            exist = Job.objects.get(slug=m)
        
            while exist:
                temp=m
                temp+=(str)(random.randint(1,1000000))
                exist = Job.objects.get(slug=temp)
        except:
            print(temp)
            self.slug = temp
            super(Job, self).save(*args, **kwargs)

jobs/forms.py
from .models import Job
from django.forms import ModelForm 

class JobForm(ModelForm):
    
    class Meta:
        model = Job
        fields = ['title','image','location',
        'short_desc','description','category',
         'vacancy','job_type','salary','company','requerment','country']

jobs/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
import os
# Create your views here.


def jobs_all(req):
    jobs = Job.objects.all()
    paginator = Paginator(jobs, 1)
    page_number = req.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(req, 'jobs/jobs.html', {'page_obj': page_obj})


@login_required
def job_create(req):
    form = JobForm()
    if req.method == 'POST':
        form = JobForm(req.POST, req.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.profile = req.user.profile
            user.save()
            messages.success(req, 'created!')
            return redirect('jobs:jobs_all')
        else:
            messages.error(req, 'faild')
            form = JobForm()
    return render(req, 'jobs/create.html', {'form': form})


def job_detail(req, slug):
    job = Job.objects.get(slug=slug)

    return render(req, 'jobs/detail.html', {'job': job})


@login_required
def job_update(req, slug):
    profile = req.user.profile
    job = profile.job_set.get(slug=slug)
    if job is not None:
        form = JobForm(instance=job)

        if req.method == 'POST':
            form = JobForm(req.POST, req.FILES, instance=job)
            if form.is_valid():
                form.save()
                messages.success(req, 'updated!')

                return redirect('jobs:jobs_all')
            else:
                messages.error(req, 'faild!')
                form = JobForm(instance=profile)
    else:
        messages.error(req, 'not exist')

    return render(req, 'jobs/update.html', {'form': form})


def job_delete(req, slug):
    job = Job.objects.get(slug=slug)
    if req.method == 'POST':
        job.delete()
        messages.success(req, 'deleted!')
        return redirect('jobs:jobs_all')
    return render(req, 'jobs/delete.html', {})

jobs/templates/jobs/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
<div style="width: 90%; margin-left: 5%;margin-bottom: 20px;">
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input class="btn btn-primary" style="width: 100%;" type="submit" value="create">
</form>
</div>




{% endblock content %}

jobs/templates/jobs/delete.html
{% extends "base.html" %}


{% block content %}
  
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input class="btn btn-primary" 
    style="width: 80%; background-color: crimson;margin-left: 10%;margin-bottom: 20px;" type="submit" value="delete">
</form>




{% endblock content %}

jobs/templates/jobs/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}



<section id="intro">
    <div class="carousel-item active">
        <div class="carousel-background"><img src="{% static 'imags/slider/slider1.jpg' %}" alt=""></div>
        <div class="carousel-container">
            <div class="carousel-content">
                <h2 class="font-color-white">Job Result</h2>
                <p class="font-color-white width-100"><a href="index.html" class="font-color-white">Home /</a><a
                        href="Job_Category-2.html" class="font-color-white"> Job </a>/ Details
                </p>
            </div>
        </div>
    </div>
</section>


<section id="job-Details">
    <div class="container background-color-full-white job-Details">
        <div class="Exclusive-Product">
            <h3>{{job.title}}</h3>
            {% if job.profile == user.profile %}
              <a href="{% url 'jobs:job_delete' job.slug %}" class="Apply-Now">Delete</a>
            <a href="{% url 'jobs:job_update' job.slug %}" class="Apply-Now">Edit</a>
            {% else %}
                <a href="#" class="Apply-Now">Apply Now</a>
            {% endif %}
            
            <h6 class="font-color-orange">{{job.company}}</h6>
            <a href="{% url 'profiles:profile_detail' job.profile.slug %}" 
            style="text-decoration: none; color: black;font-size: 20px;">
            created by <span style="font-size: 25px; color: darkcyan; ">{{job.profile}}</span>
        </a>
            <i class="material-icons">place</i>
            <span class="text">{{job.location}}</span>
            <h4>Short description</h4>
            <p>{{job.short_desc}}</p>
        </div>
        
        {% if job.image %}
          <img src="{{job.image.url}}" alt="" class="job-detail-img">
          {% else %}
          <img src="{% static 'images/job.jpeg' %}" alt="John Doe" class="mr-3 " 
                style="width: 120px; height: 120px;">
        {% endif %}
        
     
     
        <div class="Job-Description">
            <h4>Job Description / Responsibility</h4>
            <ul>
                {{job.description}}
            </ul>
            <div class="vertical-space-20"></div>
            <h4>Experience & Requirement</h4>
            <p class="margin-bottom">{{job.requerment}}</p>
            <ul>
                </ul>
        </div>
    </div>
</section>


<section id="comment" class="background-color-full-white-light">
    <div class="container">
        <div class="max-width-80">
            <h4>comment</h4>
            <a href="#" class="Share">Share</a>
            <div class="media border p-3">
                <img src="imags/comment1.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <h6>Rehmatun Nisal</h6>
                    <p>Suspendisse augue pulvinar placerat himenaeos odio nec turpis augue sem maecenas, faucibus erat
                        lacinia consectetur sapien suscipit vestibulum venenatis himenaeos.</p>
                </div>
            </div>
            <div class="media border p-3 ">
                <img src="imags/comment2.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <h6>Rehmatun Nisal</h6>
                    <p>Suspendisse augue pulvinar placerat himenaeos odio nec turpis augue sem maecenas, faucibus erat
                        lacinia consectetur sapien suscipit vestibulum venenatis himenaeos.</p>
                </div>
            </div>
            <div class="media border p-3 padding-none border-none">
                <img src="imags/comment3.png" alt="John Doe" class="mr-3 rounded-circle imagess" style="width:60px;">
                <div class="media-body">
                    <form>
                        <textarea placeholder="Type commeny" required></textarea>
                        <button class="Post">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>




{% endblock content %}

jobs/templates/jobs/jobs.html
{% extends "base.html" %}
{% load static %}

{% block content %}




<div id="search-box">
    <div class="container search-box">
        <form action="#" id="search-box_search_form_3"
            class="search-box_search_form d-flex flex-lg-row flex-column align-items-center justify-content-between ">
            <div class="d-flex flex-row align-items-center justify-content-start inline-block">
                <span class="large material-icons search">search</span>
                <input class="search-box_search_input" placeholder="Search Keyword" required="required" type="search">
                <select class="dropdown_item_select search-box_search_input">
                    <option>Category</option>
                    <option>Category1</option>
                    <option>Category2</option>
                </select>
                <span class="large material-icons search">place</span>
                <input class="search-box_search_input " placeholder="Location" required="required" type="search">
            </div>
            <button type="submit" class="search-box_search_button">Search Jobs</button>
        </form>
    </div>
</div>


<section id="resent-job-post" class="background-color-white">
    <div class="vertical-space-85"></div>
    <div class="container text-center">
        <h3 class="text-center">Recent Job Post</h3>
        <div class="vertical-space-30"></div>
        <p class="max-width">Lorem ipsum tempus amet conubia adipiscing fermentum viverra gravida, mollis suspendisse
            pretium dictumst inceptos mattis euismod
        </p>
        <div class="vertical-space-60"></div>
        {% for job in page_obj %}
        <div class="detail">
            <div class="media display-inline text-align-center">
                {% if job.image %}
                <img src="{{job.image.url}}" alt="John Doe" class="mr-3 " style="width: 120px; height: 120px;">
                {% else %}
                <img src="{% static 'images/job.jpeg' %}" alt="John Doe" class="mr-3 "
                    style="width: 120px; height: 120px;">
                {% endif %}


                <div class="media-body text-left  text-align-center">
                    <a href="{% url 'jobs:job_detail' job.slug %}">
                        <h6>{{job.title}}</h6>
                    </a>
                    <i class="large material-icons">account_balance</i>
                    <span class="text">{{job.country}}</span>
                    <br />
                    <i class="large material-icons">place</i>
                    <span class="text font-size">{{job.location}}</span>
                    <div class="float-right margin-top text-align-center">
                        <a href="#" class="part-full-time">{{job.job_type}}</a>
                        <p class="date-time">Published at: {{job.pubished_at}}</p>
                    </div>
                </div>

            </div>
            <a href="{% url 'profiles:profile_detail' job.profile.slug %}"
                style="text-decoration: none; font-size: 18px;">created by:<span
                    style="font-size: 25px;margin-left: 5px;">{{job.profile}}</span></a>

        </div>
        {% endfor %}




        <div class="vertical-space-20"></div>
        <div class="job-list">

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div>



    </div>
    <div class="vertical-space-60"></div>
</section>




{% endblock content %}

jobs/templates/jobs/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
  
<div style="margin-bottom: 20px; width:90%; margin-left: 5%;">
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input class="btn btn-primary" style="width: 100%;" type="submit" value="update">
</form>
</div>




{% endblock content %}